version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.1.0
    working_directory: ~/mailtrap-client
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "./package.json" }}
      - run:
          name: "lint"
          command: |
            npm install
            npm run lint
      - save_cache:
          key: npm-dependency-cache-{{ checksum "./package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:10.1.0
    working_directory: ~/mailtrap-client
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "./package-lock.json" }}
      - run:
          name: "test"
          command: |
            npm install
            npm run test:integration
      - save_cache:
          key: npm-dependency-cache-{{ checksum "./package-lock.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: circleci/node:10.1.0
    working_directory: ~/mailtrap-client
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "./package-lock.json" }}
      - run:
          name: "test"
          command: |
            npm install
            npm run build
      - save_cache:
          key: npm-dependency-cache-{{ checksum "./package-lock.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  build-test-publish:
    jobs:
      - lint
      - test
      - build
